### ISSUE TITLE
Complex product should be used in eltwise product

### ISSUE THREAD

**Issue by vadimkantorov** [DeepInsight-PCALab/CompactBilinearPooling-Pytorch#3]
I was investigating differences in results of this package and of the original Caffe version. Things found so far:
1. Rfft can be used directly, it is provided by pytorch_fft
2. Complex product should be used here: https://github.com/DeepInsight-PCALab/CompactBilinearPooling-Pytorch/blob/master/CompactBilinearPooling.py#L91, the tf.multiply does complex product, original caffe version does complex product
3. Output should be mutliplied by `output_dim` in order to achieve full equivalence with original caffe version

**Comment by dichen-cd** [comment]
Many thanks for your advice! I will investigate into that later!

**Comment by Yosshi999** [comment]
In https://github.com/DeepInsight-PCALab/CompactBilinearPooling-Pytorch/blob/master/CompactBilinearPooling.py#L91, this calculation means `(a+bi)*(c+di)=ac+bdi`.
I think this line should be:
`fft_product_real = fft1_real.mul(fft2_real) - fft1_imag.mul(fft2_imag)`
and
`fft_product_imag = fft1_real.mul(fft2_imag) - fft1_imag.mul(fft2_real)`
because `(a+bi)*(c+di)` must be `(ac-bd)+(bc+ad)i`.

**Comment by dichen-cd** [comment]
After some doc rushing I think `tf.multiply ` does element-wise product instead of complex product. The comment at [L141](https://github.com/ronghanghu/tensorflow_compact_bilinear_pooling/blob/master/compact_bilinear_pooling.py#L141) also indicates that. And if this is true, element-wise on the real part and imag part respectively should be equivalent to element-wise product at the two parts at once.

**Comment by vadimkantorov** [comment]
from my tests, it's the complex product that matches the original Caffe version

very roughly based on your code, i made a version that uses new PyTorch fft support: https://gist.github.com/vadimkantorov/d9b56f9b85f1f4ce59ffecf893a1581a

**Comment by dichen-cd** [comment]
Awesome!

I'll check the caffe version later.

**Comment by vadimkantorov** [comment]
a link to original author's caffe impl (complex product): https://github.com/gy20073/compact_bilinear_pooling/blob/master/caffe-20160312/src/caffe/layers/compact_bilinear_layer.cpp#L219

if `tf.multiply` doesn't do complex product, it may be a bug in the tf reimpl

**Comment by dichen-cd** [comment]
Checked the original paper again. Although the paper doesn't make an explicit statement, I believe u r right. It makes more sense for element-wise complex product than naive production.

Many thanks for your help! I'll update this repo soon.
